# Generated by Django 3.1.4 on 2021-01-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210109_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='facebook_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(default=''),
        ),
    ]
